# This is a basic workflow to help you get started with Actions
# 配置参考 https://github.com/alanbobs999/TopFreeProxies

name: CI

# Controls when the workflow will run

on:
  schedule:
    # Executed at 5:00, 19:00 o'clock every day
    # 表达式生成  https://crontab.guru/
    - cron:  '0 3,9,15,21 * * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./requirements
    - name: 执行任务
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
        python ./scripts/merge.py
      
    - name: 提交合并
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./merge
        git add v2ray
        git commit -m "merge: $(date '+%Y-%m-%d %H:%M:%S') 合并节点"
    - name: 推送合并
      uses:  ad-m/github-push-action@master
      with:
        branch: master
    - name: 提交链接
      run: |                 
        if [[ -z $(git status --porcelain) ]]
        then
          echo "链接无更新"
        else
          git pull origin master
          git add list.json
          git commit -m "update: $(date '+%Y-%m-%d %H:%M:%S') 更新链接"
        fi
    - name: 推送链接
      uses:  ad-m/github-push-action@master
      with:
        branch: master
